"""Run blastp against the built reference database.

One invocation covers every sequence in the submission; the results are split
per query afterwards. Nothing user-controlled reaches the command line: the
query file contains internal `Q<n>` identifiers only, and every path argument
is generated by the server.
"""

from __future__ import annotations

import logging
from pathlib import Path

from app.config import Settings
from app.schemas import ErrorCode
from app.search.outcome import SearchOutcome
from app.search.parsers import BLAST_OUTFMT, ParseError, parse_blast_tabular, rank_hits
from app.search.subprocess_utils import ToolNotFound, run_tool, tool_version

log = logging.getLogger(__name__)


def blastp_args(settings: Settings, query_fasta: Path, out_path: Path) -> list[str]:
    """Build the exact blastp argument list used by the request path."""
    return [
        "-query", str(query_fasta),
        "-db", str(settings.blast_db),
        "-outfmt", BLAST_OUTFMT,
        "-out", str(out_path),
        "-evalue", str(settings.blast_evalue),
        "-max_target_seqs", str(settings.blast_max_target_seqs),
        "-num_threads", str(settings.search_threads),
        # Composition-based statistics (Yu, Wootton & Altschul 2003) is
        # blastp's default and is what makes E-values from a compositionally
        # biased query trustworthy. Stated explicitly so a future change to it
        # is a visible decision rather than a silent default drift.
        "-comp_based_stats", "2",
    ]


def run_blastp(settings: Settings, job_dir: Path, query_fasta: Path) -> SearchOutcome:
    db = settings.blast_db
    # .pin is the index makeblastdb always writes for a protein database;
    # its absence means the build step never ran or did not finish.
    built = db.parent.exists() and any(db.parent.glob(db.name + "*.pin"))
    if not built:
        return SearchOutcome.failure(
            "blastp", ErrorCode.REFERENCE_MISSING,
            "The BLAST reference database has not been built on this server.",
        )

    out_path = job_dir / "blastp_hits.tsv"
    args = blastp_args(settings, query_fasta, out_path)

    try:
        run = run_tool(
            settings.blastp_bin, args,
            timeout=settings.blast_timeout_seconds,
            log_dir=job_dir, log_name="blastp",
        )
    except ToolNotFound:
        return SearchOutcome.failure(
            "blastp", ErrorCode.EXECUTABLE_MISSING,
            "BLAST+ is not installed on this server.",
        )

    version = tool_version(settings.blastp_bin, ["-version"])
    if run.timed_out:
        return SearchOutcome.failure(
            "blastp", ErrorCode.TIMEOUT,
            f"BLAST did not finish within {settings.blast_timeout_seconds} seconds.",
            version=version, runtime=run.duration,
        )
    if run.returncode != 0:
        return SearchOutcome.failure(
            "blastp", ErrorCode.NONZERO_EXIT,
            "BLAST exited with an error. The raw output has been kept for diagnosis.",
            version=version, runtime=run.duration,
        )

    try:
        text = out_path.read_text(encoding="utf-8", errors="replace") if out_path.exists() else ""
        hits = parse_blast_tabular(text)
    except (ParseError, OSError) as exc:
        log.warning("blastp output unparseable: %s", exc)
        return SearchOutcome.failure(
            "blastp", ErrorCode.OUTPUT_UNPARSEABLE,
            "BLAST produced output this server could not read.",
            version=version, runtime=run.duration,
        )

    return SearchOutcome(
        method="blastp",
        version=version,
        runtime=run.duration,
        hits_by_query=rank_hits(hits, settings.max_hits_per_query),
    )
